name: Deploy to Shinyapps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install shiny
        run: |
          install.packages(c("shiny", "maps", "leaflet", "dplyr", "rsconnect", "countrycode", "tidygeocoder"))
        shell: Rscript {0}
      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='open-life-science', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')"
          Rscript -e "rsconnect::deployApp(appName = 'ols_community_map')"