# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]

name: Deploy to Shinyapps

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Install rsconnect
        run: install.packages("rsconnect")
        shell: Rscript {0}

      - name: Install shiny
        run: install.packages("shiny")
        shell: Rscript {0}

      - name: Install maps
        run: install.packages("maps")
        shell: Rscript {0}

      - name: Install leaflet
        run: install.packages("leaflet")
        shell: Rscript {0}

      - name: Install dplyr
        run: install.packages("dplyr")
        shell: Rscript {0}

      - name: Install countrycode
        run: install.packages("countrycode")
        shell: Rscript {0}

      - name: Install tidygeocoder
        run: install.packages("tidygeocoder")
        shell: Rscript {0}

      - name: Install tidyverse
        run: install.packages("tidyverse")
        shell: Rscript {0}

      - name: Authorize and deploy app
        env: 
          # Provide your app name, account name, and server to be deployed below
          APPNAME: ols_community_map
          SERVER: shinyapps.io # server to deploy
        run: |
          rsconnect::setAccountInfo(name = "open-life-science", token = "${{ secrets.SHINYAPPS_TOKEN }}", secret = "${{ secrets.SHINYAPPS_SECRET }}")
          rsconnect::deployApp(appName = "${{ env.APPNAME }}", server = "${{ env.SERVER }}")
        shell: Rscript {0}